# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/Final_Project_Constraints.xdc

# IP: ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
