# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.runs/synth_1/WimpFi_Hardware_TL.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.cache/wt} [current_project]
set_property parent.project_path {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.xpr} [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/FSM_MX_RCVR.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/FSM_MX_XMIT.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/FSM_UART_RCVR.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/FSM_UART_XMIT.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/WimpFi_Network_Interface.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/WimpFi_Receiver.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/WimpFi_Transmitter.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/board_interfacing.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/button_single_pulser.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/correlator.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/counter.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/crc.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/crc_lookup.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/dec_3_8.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/fsafe.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/fsafe_fsm.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/mem2p_sw_sr.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/mux8_seven_Seg.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/mx_data_constructor.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/mx_rcvr_TL.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/mx_rcvr_shreg.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/mx_xmit_TL.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/mx_xmit_shreg.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/rate_enb.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/rcvr_adapter.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/sevenseg_ctl.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/sevenseg_ext.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/sh_reg_uart_rcvr.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/sh_reg_uart_xmit.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/uart_rcvr_TL.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/uart_xmit_TL.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/xmit_adapter.sv}
  {D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/new/WimpFi_Hardware_TL.sv}
}
read_ip -quiet {{D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/WimpFi_Final_Project.gen/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc}}]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/Final_Project_Constraints.xdc}}
set_property used_in_implementation false [get_files {{D:/Scool/ECE 416/ece416_Bachman_Beal/WimpFi_Final_Project/Final_Project_Constraints.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top WimpFi_Hardware_TL -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef WimpFi_Hardware_TL.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file WimpFi_Hardware_TL_utilization_synth.rpt -pb WimpFi_Hardware_TL_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
